#!/usr/bin/env python3
"""
Generate esp_foc_autotuned_gains.h from a motor profile JSON.

Mirrors the Matched Pole-Zero (MPZ) synthesis in
source/motor_control/esp_foc_design_mpz.c so that build-time autogen and
runtime tuning produce the same gains for the same inputs.

Designed to be called from CMake; refuses to write inside source/ or include/
unless --allow-in-tree is passed (defensive against accidental commits).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from dataclasses import dataclass

Q16_ONE = 1 << 16
INT32_MAX = 2**31 - 1
INT32_MIN = -(2**31)


def to_q16(x: float) -> int:
    v = round(x * Q16_ONE)
    if v > INT32_MAX:
        v = INT32_MAX
    if v < INT32_MIN:
        v = INT32_MIN
    return int(v)


def q16_to_hex(x: int) -> str:
    if x < 0:
        x &= 0xFFFFFFFF
    return f"0x{x:08X}"


@dataclass
class DesignResult:
    kp: float
    ki: float
    integrator_limit: float
    alpha: float
    beta: float
    loop_ts_us: int
    pwm_rate_hz: int
    decimation: int
    bw_hz: float
    r_ohm: float
    l_h: float
    v_max: float
    phase_margin_deg_no_delay: float
    phase_margin_deg_one_sample_delay: float


def design_mpz(r_ohm: float, l_h: float, loop_ts_s: float,
               bw_hz: float, v_max: float) -> DesignResult:
    if r_ohm <= 0 or l_h <= 0 or loop_ts_s <= 0 or bw_hz <= 0 or v_max <= 0:
        raise ValueError("all design parameters must be positive")
    if bw_hz * loop_ts_s >= 0.5:
        raise ValueError(
            f"bandwidth {bw_hz} Hz exceeds Nyquist for Ts={loop_ts_s*1e6:.1f}us "
            f"(bw*Ts={bw_hz*loop_ts_s:.3f} >= 0.5)"
        )

    omega_bw = 2.0 * math.pi * bw_hz
    alpha = math.exp(-r_ohm * loop_ts_s / l_h)
    beta = math.exp(-omega_bw * loop_ts_s)
    one_minus_alpha = 1.0 - alpha
    one_minus_beta = 1.0 - beta
    if one_minus_alpha <= 0 or one_minus_beta <= 0:
        raise ValueError("degenerate design (alpha or beta out of range)")

    kp = r_ohm * one_minus_beta / one_minus_alpha
    ki = r_ohm * one_minus_beta / loop_ts_s

    # Phase margin estimates (see derivation in design_mpz.h commentary)
    pm_arg = one_minus_beta / 2.0
    pm_arg = min(max(pm_arg, -1.0), 1.0)
    omega_c_ts = 2.0 * math.asin(pm_arg)
    pm_no_delay = math.pi / 2.0 - math.asin(pm_arg)
    # One-sample computation delay adds -omega_c*Ts to the phase
    pm_one_sample = pm_no_delay - omega_c_ts

    return DesignResult(
        kp=kp,
        ki=ki,
        integrator_limit=v_max,
        alpha=alpha,
        beta=beta,
        loop_ts_us=int(round(loop_ts_s * 1e6)),
        pwm_rate_hz=0,  # set by caller
        decimation=0,   # set by caller
        bw_hz=bw_hz,
        r_ohm=r_ohm,
        l_h=l_h,
        v_max=v_max,
        phase_margin_deg_no_delay=math.degrees(pm_no_delay),
        phase_margin_deg_one_sample_delay=math.degrees(pm_one_sample),
    )


def render_header(profile_name: str, json_path: str, res: DesignResult) -> str:
    lines = [
        "/* AUTO-GENERATED by scripts/gen_pi_gains.py — DO NOT EDIT */",
        f"/* Source profile: {profile_name} ({os.path.basename(json_path)}) */",
        "#pragma once",
        "",
        "#include \"espFoC/utils/esp_foc_q16.h\"",
        "",
        "/* Motor + control context (Q16) */",
        f"#define ESP_FOC_AUTOGEN_MOTOR_R_OHM_Q16        ((q16_t){q16_to_hex(to_q16(res.r_ohm))})  /* {res.r_ohm:.6f} ohm */",
        f"#define ESP_FOC_AUTOGEN_MOTOR_L_H_Q16          ((q16_t){q16_to_hex(to_q16(res.l_h))})  /* {res.l_h*1e6:.3f} uH */",
        f"#define ESP_FOC_AUTOGEN_PWM_RATE_HZ            {res.pwm_rate_hz}",
        f"#define ESP_FOC_AUTOGEN_DECIMATION             {res.decimation}",
        f"#define ESP_FOC_AUTOGEN_LOOP_TS_US             {res.loop_ts_us}",
        f"#define ESP_FOC_AUTOGEN_TARGET_BW_HZ_Q16       ((q16_t){q16_to_hex(to_q16(res.bw_hz))})  /* {res.bw_hz:.3f} Hz */",
        f"#define ESP_FOC_AUTOGEN_V_MAX_Q16              ((q16_t){q16_to_hex(to_q16(res.v_max))})  /* {res.v_max:.3f} V */",
        "",
        "/* Design artifacts (Q16) */",
        f"#define ESP_FOC_AUTOGEN_ALPHA_Q16              ((q16_t){q16_to_hex(to_q16(res.alpha))})  /* {res.alpha:.6f} */",
        f"#define ESP_FOC_AUTOGEN_BETA_Q16               ((q16_t){q16_to_hex(to_q16(res.beta))})  /* {res.beta:.6f} */",
        "",
        "/* Current-loop PI gains (espFoC PID convention, Q16) */",
        f"#define ESP_FOC_AUTOGEN_CURRENT_KP_Q16         ((q16_t){q16_to_hex(to_q16(res.kp))})  /* {res.kp:.6f} V/A */",
        f"#define ESP_FOC_AUTOGEN_CURRENT_KI_Q16         ((q16_t){q16_to_hex(to_q16(res.ki))})  /* {res.ki:.3f} V/(A*s) */",
        f"#define ESP_FOC_AUTOGEN_CURRENT_INT_LIM_Q16    ((q16_t){q16_to_hex(to_q16(res.integrator_limit))})  /* {res.integrator_limit:.3f} V */",
        "",
        "/* Stability report (deg) */",
        f"#define ESP_FOC_AUTOGEN_PHASE_MARGIN_DEG       {int(round(res.phase_margin_deg_no_delay))}",
        f"#define ESP_FOC_AUTOGEN_PHASE_MARGIN_DELAY_DEG {int(round(res.phase_margin_deg_one_sample_delay))}",
        "",
    ]
    return "\n".join(lines)


def render_report(profile_name: str, json_path: str, res: DesignResult) -> str:
    return (
        f"espFoC PI autotuning report\n"
        f"===========================\n"
        f"Profile     : {profile_name} ({os.path.basename(json_path)})\n"
        f"Motor       : R = {res.r_ohm:.6f} ohm, L = {res.l_h*1e6:.3f} uH\n"
        f"Loop        : PWM = {res.pwm_rate_hz} Hz, decimation = {res.decimation}, "
        f"Ts = {res.loop_ts_us} us\n"
        f"Target BW   : {res.bw_hz:.3f} Hz (bw*Ts = {res.bw_hz*res.loop_ts_us*1e-6:.4f})\n"
        f"V max       : {res.v_max:.3f} V\n"
        f"\n"
        f"Discrete plant pole alpha = exp(-R*Ts/L) = {res.alpha:.6f}\n"
        f"Closed-loop pole    beta  = exp(-w_bw*Ts) = {res.beta:.6f}\n"
        f"\n"
        f"Kp                 = {res.kp:.6f} V/A\n"
        f"Ki                 = {res.ki:.3f} V/(A*s)\n"
        f"Integrator limit   = {res.integrator_limit:.3f} V\n"
        f"\n"
        f"Phase margin (no delay)        : {res.phase_margin_deg_no_delay:.1f} deg\n"
        f"Phase margin (1-sample delay)  : {res.phase_margin_deg_one_sample_delay:.1f} deg\n"
    )


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--motor", required=True, help="path to motor profile JSON")
    p.add_argument("--output", required=True, help="output header path")
    p.add_argument("--report", help="optional output path for human-readable report")
    p.add_argument("--pwm-rate-hz", type=int, required=True,
                   help="PWM frequency the inverter is driven at, in Hz")
    p.add_argument("--decimation", type=int, required=True,
                   help="current loop decimation factor (1 = ISR-mode)")
    p.add_argument("--allow-in-tree", action="store_true",
                   help="permit writing under source/ or include/ (NOT recommended)")
    return p.parse_args()


def guard_output_path(path: str, allow_in_tree: bool) -> None:
    """Refuse to write inside source/ or include/ unless explicitly allowed."""
    abspath = os.path.abspath(path)
    forbidden_segments = (os.sep + "source" + os.sep,
                          os.sep + "include" + os.sep,
                          os.sep + "scripts" + os.sep + "motors" + os.sep)
    for seg in forbidden_segments:
        if seg in abspath:
            if allow_in_tree:
                return
            sys.stderr.write(
                f"ERROR: output {abspath} would land inside the source tree.\n"
                f"       Pass --allow-in-tree to override (NOT recommended; the\n"
                f"       generated file would risk entering git staging).\n"
            )
            sys.exit(2)


def main() -> int:
    args = parse_args()
    guard_output_path(args.output, args.allow_in_tree)
    if args.report is not None:
        guard_output_path(args.report, args.allow_in_tree)

    if args.pwm_rate_hz <= 0:
        sys.stderr.write("ERROR: --pwm-rate-hz must be positive\n")
        return 2
    if args.decimation <= 0:
        sys.stderr.write("ERROR: --decimation must be positive\n")
        return 2

    try:
        with open(args.motor, "r") as f:
            profile = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        sys.stderr.write(f"ERROR: cannot read motor profile: {e}\n")
        return 3

    try:
        name = profile.get("name", os.path.basename(args.motor))
        motor = profile["motor"]
        control = profile["control"]
        safety = profile.get("safety", {})
        r_ohm = float(motor["resistance_ohm"])
        l_h = float(motor["inductance_h"])
        bw_hz = float(control["current_bw_hz"])
        v_max = float(control["v_max_volts"])
        min_pm = float(safety.get("min_phase_margin_deg", 30.0))
    except (KeyError, TypeError, ValueError) as e:
        sys.stderr.write(f"ERROR: invalid motor profile schema: {e}\n")
        return 3

    loop_ts_s = float(args.decimation) / float(args.pwm_rate_hz)

    try:
        res = design_mpz(r_ohm, l_h, loop_ts_s, bw_hz, v_max)
    except ValueError as e:
        sys.stderr.write(f"ERROR: design failed: {e}\n")
        return 4
    res.pwm_rate_hz = args.pwm_rate_hz
    res.decimation = args.decimation

    pm = res.phase_margin_deg_one_sample_delay
    if pm < min_pm:
        sys.stderr.write(
            f"ERROR: phase margin (with 1-sample delay) {pm:.1f} deg < "
            f"required {min_pm:.1f} deg. Reduce target bandwidth or revisit "
            f"the motor profile.\n"
        )
        return 5
    if pm < 45.0:
        sys.stderr.write(
            f"WARNING: phase margin (with 1-sample delay) is only {pm:.1f} deg.\n"
        )
    if l_h < 5e-4:
        sys.stderr.write(
            f"WARNING: inductance {l_h*1e6:.1f} uH is below the Q16 precision "
            f"floor (~500 uH). Runtime gains may differ from this report.\n"
        )

    os.makedirs(os.path.dirname(os.path.abspath(args.output)), exist_ok=True)
    with open(args.output, "w") as f:
        f.write(render_header(name, args.motor, res))

    if args.report is not None:
        os.makedirs(os.path.dirname(os.path.abspath(args.report)), exist_ok=True)
        with open(args.report, "w") as f:
            f.write(render_report(name, args.motor, res))

    print(f"espFoC PI autotuner: {args.output} generated "
          f"(Kp={res.kp:.4f} V/A, Ki={res.ki:.2f} V/(A*s), "
          f"PM_delay={pm:.1f} deg)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
